dist: trusty
sudo: required
language: bash
env:
  global:
    PACKER_VERSION: '1.4.4'
    TERRAFORM_VERSION: '0.12.8'
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-08/run.sh | bash
install:
  # install ansible linter
  - |
    # pip install --upgrade pip
    pip install --user ansible-lint
    ansible-lint --version
  # Install Hashicorp's packer
  - |
    curl -L -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
    unzip -d ~/bin packer.zip
    packer version  
  # Install terraform
  - |
    curl -L -o terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
    unzip -d ~/bin terraform.zip
    terraform --version
  # Install tflint
  - |
    curl https://raw.githubusercontent.com/wata727/tflint/master/install_linux.sh | bash
    tflint --version
script:
  - packer validate -var-file=packer/variables.json.example packer/db.json
  - packer validate -var-file=./packer/variables.json.example ./packer/app.json
  - cd terraform/prod && terraform get && cd ../..
  - cd terraform/prod && terraform init -backend=false && cd ../..
  - cd terraform/prod && terraform validate && cd ../..
  - cd terraform/stage && terraform get && cd ../..
  - cd terraform/stage && terraform init -backend=false && cd ../..
  - cd terraform/stage && terraform validate && cd ../..
  - tflint terraform/prod
  - tflint terraform/stage
  # Закомментровал для прохождения тестов, так как из-за отсутствия ключа для vault не проходят - жду ответа от Станислава Стурова в Slack
  # - cd ansible && ansible-playbook playbooks/site.yml --syntax-check && cd ..
  - ansible-lint -v ansible/playbooks/site.yml
notifications:
  slack:
    rooms:
      secure: DgVKZz1y+7Ze3qdmX82oRIoITjypoCA8n9QIq8V5wqkzTRQRBXGsWasqV+VrqpdeqrA5QVnEtcmNHqt6HrmKei5wtd/FJqYMiiUQhpmhjqVASfZ667tiNZqmj9OOpf94htzEKgY/JfslFXfLEogUMJa+dzsoXZCBKuBFWHN16uKpviQ1/bAJhKHwO2cTz+nsTCUv11EyGUv9U/on/wQ8ySTbiWFK9Z3y00OqzhByq/9zuwoxcZgW7acxehtyHYALiYAxvx2kQv4Dv4dra6ng0m7bObiwCU07R3KgKfdoxL1RZwWZmvzLLmxmtBqJ0uZ9+NCLh3FbhKppBa4g3wZyxrvklsQ2TXvziDfqcHbz7s1+FzWHb74keiRO/5GOjt0olcv80/k1Ma4oBW0AgMzZ4AqGcFMLE9Dg3bh4EBd3mUQ1YVc+a0qx3e9MhCq0sBnjUZbJtH08Z/wyTywXyTZNPWdhyZUNJS89C5btw2zDdnFSD+8nrYoji4XckZgoYT3sgadXzAteJ70DyU7TejG1ieKPCcapJi41myeL+Gyp8CFZxZJNIvMtWU177dZeCS6j7HTYTz/b9obTkIuLJ/RIrGZR25oYbiz1QsRCmJMj1uCAeT1Jfh5HgsQmInzS3q0MGiJrOO+aivttMXD9+I4633KXnIDKB+qUb6koXDIRhXI=
