---
- name: Install mongodb
  hosts: all
  become: true
  tasks:
    - apt: update_cache=yes upgrade=safe cache_valid_time=3600
    - name: Add apt-key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: D68FA50FEA312927
    - name: Add APT repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        # state: present # default
    - name: Install mongodb
      apt:
        name: mongodb-org
        force_apt_get: yes
        state: present
    - name: Start mongodb service
      service:
        name: mongod
        enabled: yes
